In [1]:
import numpy as np 

In [2]:
arr=np.array([2,3,4,5,8,9,10])

In [3]:
arr

array([ 2,  3,  4,  5,  8,  9, 10])

In [4]:
# get the mean
np.mean(arr)

np.float64(5.857142857142857)

In [5]:
# get standard deviation 
np.std(arr)

np.float64(2.899683304312063)

In [6]:
# variance of array
np.var(arr)

np.float64(8.408163265306124)

In [7]:
# minimum value
np.min(arr)

np.int64(2)

In [8]:
np.max(arr)

np.int64(10)

In [9]:
np.sum(arr)

np.int64(41)

In [10]:
#  Compute the product of all elements in an array.
np.prod(arr)

np.int64(86400)

In [11]:
# Compute the median of an array.
np.median(arr)

np.float64(5.0)

In [12]:
# percentile of array
np.percentile(arr, 50)  # For the 50th percentile (median)

np.float64(5.0)

In [13]:
# index of minimum value of array
np.argmin(arr)

np.int64(0)

In [14]:
np.argmax(arr)

np.int64(6)

In [16]:
arr2=([12,3,4,6])
arr1=([23,4,6,7])

In [17]:
# correlation coefficient 
np.corrcoef(arr1, arr2)

array([[1.       , 0.9821597],
       [0.9821597, 1.       ]])

In [18]:
# unique elements of array
np.unique(arr)

array([ 2,  3,  4,  5,  8,  9, 10])

In [19]:
# nth differences of array
np.diff(arr)

array([1, 1, 1, 3, 1, 1])

In [20]:
# cumilative sum 
np.cumsum(arr)

array([ 2,  5,  9, 14, 22, 31, 41])

In [21]:
# – Create an array with evenly spaced numbers over a specified interval.
np.linspace(0, 10, 5)  # 5 numbers from 0 to 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
# Compute the natural logarithm of an array.
np.log(arr)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 2.07944154,
       2.19722458, 2.30258509])

In [ ]:
# exponent