In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40])
print(arr[0])  # 10
print(arr[-1]) # 40

10
40


In [3]:
flat=arr.flatten()

In [4]:
flat

array([10, 20, 30, 40])

In [5]:
# extracting parts of an array
print(arr[1:4])  # [20 30 40] (slice from index 1 to 3)
print(arr[:3])   # [10 20 30] (first 3 elements)
print(arr[::2])  # [10 30 50] (every 2nd element)

[20 30 40]
[10 20 30]
[10 30]


In [6]:
sliced = arr[1:4]
sliced[0] = 999
print(arr)  # [10 999 30 40 50]

[ 10 999  30  40]


In [7]:
# slicing returns view not a copy changes affect the original array

In [8]:
# use .copy if we need an independent copy 
arr1 = np.array([10, 20, 30, 40,50])

In [10]:
arr1

array([10, 20, 30, 40, 50])

In [11]:
b=arr1.flatten()

In [12]:
b

array([10, 20, 30, 40, 50])

In [13]:
# fancy indexing selecting multiple elements 
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 30 50]


In [14]:
# boolean masking 
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[30 40 50]


In [15]:
# 1. Create a 3×3 array filled with random numbers and print its shape
array_random = np.random.rand(3, 3)
print("3x3 Random Array:\n", array_random)
print("Shape:", array_random.shape)

# 2. Convert an array of floats [1.1, 2.2, 3.3] into integers
float_array = np.array([1.1, 2.2, 3.3])
int_array = float_array.astype(int)
print("Converted to Integers:", int_array)

# 3. Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6]
arr = np.array([1, 2, 3, 4, 5, 6])
even_indices = np.where(arr % 2 == 0)[0]
even_numbers = arr[even_indices]
print("Even Numbers using Fancy Indexing:", even_numbers)

# 4. Reshape a 1D array of size 9 into a 3×3 matrix
array_1d = np.arange(9)
reshaped_array = array_1d.reshape(3, 3)
print("Reshaped 3x3 Array:\n", reshaped_array)

# 5. Use boolean masking to filter numbers greater than 50 in an array
arr2 = np.array([10, 55, 23, 78, 42, 100])
filtered = arr2[arr2 > 50]
print("Numbers > 50:", filtered)

3x3 Random Array:
 [[0.426465   0.41058074 0.60852864]
 [0.9234362  0.50264827 0.77707483]
 [0.5699505  0.38318268 0.58162897]]
Shape: (3, 3)
Converted to Integers: [1 2 3]
Even Numbers using Fancy Indexing: [2 4 6]
Reshaped 3x3 Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Numbers > 50: [ 55  78 100]
