In [1]:
import numpy as np 

In [2]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

In [3]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# axis 0 is rows and axis 1 is columns 
arr[0]

array([1, 2, 3])

In [5]:
print(np.sum(arr,axis=0))

[12 15 18]


In [6]:
print(np.sum(arr,axis=1))

[ 6 15 24]


In [7]:
# indexing in multidimensional arrays 
arr[0][1]

np.int64(2)

In [8]:
arr[0,1]

np.int64(2)

In [9]:
print(arr[0,1])

2


In [11]:
print(arr[0:2,1:3])

[[2 3]
 [5 6]]


In [12]:
# indexing in 3d arrays
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
 
# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [13]:
# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6
 
print(arr3D[:, 0, :])   # Get the first row from both sheets

6
[[1 2 3]
 [7 8 9]]


In [14]:
# Get all rows of the first column
first_col = arr[:, 0]
print(first_col)  # Output: [1 4 7]

[1 4 7]


In [15]:
# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

[[1 2 3]
 [7 8 9]]


In [16]:
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]


In [17]:
arr

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])