In [1]:
import numpy as np 

In [2]:
arr=np.array([1,3,4])

In [3]:
arr

array([1, 3, 4])

In [5]:
arr2=np.array([[1,2,3],[4,5,6]])

In [6]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
z=np.zeros((3,4))

In [9]:
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
a=np.ones((3,5))

In [12]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [14]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.arange(1,10,2) 
# range

array([1, 3, 5, 7, 9])

In [17]:
np.linspace(0, 1, 5) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
arr3 = np.array([[10, 20, 30], [40, 50, 60]])

In [19]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [22]:
# shape
arr3.shape

(2, 3)

In [23]:
# size
arr3.size

6

In [24]:
# dimesnsions 
arr3.ndim

2

In [25]:
# data type
arr3.dtype

dtype('int64')

In [26]:
# changing datatypes in arrays 
arr4=np.array([1,2,3],dtype=float)

In [27]:
arr4.dtype

dtype('float64')

In [28]:
arr4

array([1., 2., 3.])

In [29]:
arr_int=arr4.astype(int)

In [30]:
arr_int

array([1, 2, 3])

In [38]:
# reshaping and flattening arrays 
arr5=np.array([[1,2,3,4],[1,3,5,6]])
arr5

array([[1, 2, 3, 4],
       [1, 3, 5, 6]])

In [39]:
arr5.shape

(2, 4)

In [40]:
reshape=arr5.reshape((4,2))

In [41]:
print(reshape)

[[1 2]
 [3 4]
 [1 3]
 [5 6]]


In [42]:
#  flatten convert 2d into 1d
flat=arr5.flatten()
flat

array([1, 2, 3, 4, 1, 3, 5, 6])

In [43]:
print(flat)

[1 2 3 4 1 3 5 6]
