In [1]:
import numpy as np 

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)  # Output: int64 (or int32 depending on the system)

int64


In [3]:
# changing data types 
arr.astype("float")

array([1., 2., 3., 4., 5.])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr2=np.array([2,3,4,5],dtype="float32")

In [7]:
arr2

array([2., 3., 4., 5.], dtype=float32)

In [8]:
# downcasting to save memory 
arr_large = np.array([1000000, 2000000, 3000000], dtype=np.int64)
arr_small = arr_large.astype(np.int32)  # Downcasting to a smaller dtype
print(arr_small)  # Output: [1000000 2000000 3000000]
print(arr_small.dtype)  # Output: int32

[1000000 2000000 3000000]
int32


#  why data types matter 
## Memory Usage: Smaller data types use less memory.

## Performance: Operations on smaller data types are faster due to less data being processed.

## Precision: Choosing the appropriate data type ensures that you don't lose precision (e.g., using float32 instead of float64 if you don't need that extra precision).

In [9]:
# memory usage 
arr_int64 = np.array([1, 2, 3], dtype=np.int64)
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
 
print(arr_int64.nbytes)  # Output: 24 bytes (3 elements * 8 bytes each)
print(arr_int32.nbytes)  # Output: 12 bytes (3 elements * 4 bytes each)

24
12


In [10]:
# string data type in numpy 
# However, working with strings in NumPy is less efficient than using lists or Python's built-in string types.
arr = np.array(['apple', 'banana', 'cherry'], dtype='U10')  # Unicode string array
print(arr)

['apple' 'banana' 'cherry']


In [11]:
# complex numbers 
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


In [13]:
# object data type
# If you need to store mixed or complex data types (e.g., Python objects), you can use dtype='object'. However, this type sacrifices performance, so it should only be used when absolutely necessary.
arr3 = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr3)

[{'a': 1} list([1, 2, 3]) 'hello']
